// Generated by JavaCPP version 1.3.1: DO NOT EDIT THIS FILE

#include <jni.h>

#ifdef __cplusplus
extern "C" {
#endif
#include <opus.h>
#include <opus_types.h>
#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C" {
#endif
JNIIMPORT int JavaCPP_init(int argc, const char *argv[]);
JNIIMPORT int JavaCPP_uninit();

#ifdef __cplusplus
}
#endif
